---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop comingsoon-page-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm comingsoon-page-container
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi comingsoon-page
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t aldoun/comingsoon-page .

    - name: Push Image to dockerhub
      command: docker push aldoun/comingsoon-page

    - name: run container
      command: docker run -d --name comingsoon-page-container -p 5000:80 comingsoon-page:latest

